/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing Color
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ColorTests
    {
        // TODO uncomment below to declare an instance variable for Color
        //private Color instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Color
            //instance = new Color();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Color
        /// </summary>
        [Test]
        public void ColorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Color
            //Assert.IsInstanceOfType<Color> (instance, "variable 'instance' is a Color");
        }

        /// <summary>
        /// Test the property 'Transparent'
        /// </summary>
        [Test]
        public void TransparentTest()
        {
            // TODO unit test for the property 'Transparent'
        }
        /// <summary>
        /// Test the property 'AliceBlue'
        /// </summary>
        [Test]
        public void AliceBlueTest()
        {
            // TODO unit test for the property 'AliceBlue'
        }
        /// <summary>
        /// Test the property 'AntiqueWhite'
        /// </summary>
        [Test]
        public void AntiqueWhiteTest()
        {
            // TODO unit test for the property 'AntiqueWhite'
        }
        /// <summary>
        /// Test the property 'Aqua'
        /// </summary>
        [Test]
        public void AquaTest()
        {
            // TODO unit test for the property 'Aqua'
        }
        /// <summary>
        /// Test the property 'Aquamarine'
        /// </summary>
        [Test]
        public void AquamarineTest()
        {
            // TODO unit test for the property 'Aquamarine'
        }
        /// <summary>
        /// Test the property 'Azure'
        /// </summary>
        [Test]
        public void AzureTest()
        {
            // TODO unit test for the property 'Azure'
        }
        /// <summary>
        /// Test the property 'Beige'
        /// </summary>
        [Test]
        public void BeigeTest()
        {
            // TODO unit test for the property 'Beige'
        }
        /// <summary>
        /// Test the property 'Bisque'
        /// </summary>
        [Test]
        public void BisqueTest()
        {
            // TODO unit test for the property 'Bisque'
        }
        /// <summary>
        /// Test the property 'Black'
        /// </summary>
        [Test]
        public void BlackTest()
        {
            // TODO unit test for the property 'Black'
        }
        /// <summary>
        /// Test the property 'BlanchedAlmond'
        /// </summary>
        [Test]
        public void BlanchedAlmondTest()
        {
            // TODO unit test for the property 'BlanchedAlmond'
        }
        /// <summary>
        /// Test the property 'Blue'
        /// </summary>
        [Test]
        public void BlueTest()
        {
            // TODO unit test for the property 'Blue'
        }
        /// <summary>
        /// Test the property 'BlueViolet'
        /// </summary>
        [Test]
        public void BlueVioletTest()
        {
            // TODO unit test for the property 'BlueViolet'
        }
        /// <summary>
        /// Test the property 'Brown'
        /// </summary>
        [Test]
        public void BrownTest()
        {
            // TODO unit test for the property 'Brown'
        }
        /// <summary>
        /// Test the property 'BurlyWood'
        /// </summary>
        [Test]
        public void BurlyWoodTest()
        {
            // TODO unit test for the property 'BurlyWood'
        }
        /// <summary>
        /// Test the property 'CadetBlue'
        /// </summary>
        [Test]
        public void CadetBlueTest()
        {
            // TODO unit test for the property 'CadetBlue'
        }
        /// <summary>
        /// Test the property 'Chartreuse'
        /// </summary>
        [Test]
        public void ChartreuseTest()
        {
            // TODO unit test for the property 'Chartreuse'
        }
        /// <summary>
        /// Test the property 'Chocolate'
        /// </summary>
        [Test]
        public void ChocolateTest()
        {
            // TODO unit test for the property 'Chocolate'
        }
        /// <summary>
        /// Test the property 'Coral'
        /// </summary>
        [Test]
        public void CoralTest()
        {
            // TODO unit test for the property 'Coral'
        }
        /// <summary>
        /// Test the property 'CornflowerBlue'
        /// </summary>
        [Test]
        public void CornflowerBlueTest()
        {
            // TODO unit test for the property 'CornflowerBlue'
        }
        /// <summary>
        /// Test the property 'Cornsilk'
        /// </summary>
        [Test]
        public void CornsilkTest()
        {
            // TODO unit test for the property 'Cornsilk'
        }
        /// <summary>
        /// Test the property 'Crimson'
        /// </summary>
        [Test]
        public void CrimsonTest()
        {
            // TODO unit test for the property 'Crimson'
        }
        /// <summary>
        /// Test the property 'Cyan'
        /// </summary>
        [Test]
        public void CyanTest()
        {
            // TODO unit test for the property 'Cyan'
        }
        /// <summary>
        /// Test the property 'DarkBlue'
        /// </summary>
        [Test]
        public void DarkBlueTest()
        {
            // TODO unit test for the property 'DarkBlue'
        }
        /// <summary>
        /// Test the property 'DarkCyan'
        /// </summary>
        [Test]
        public void DarkCyanTest()
        {
            // TODO unit test for the property 'DarkCyan'
        }
        /// <summary>
        /// Test the property 'DarkGoldenrod'
        /// </summary>
        [Test]
        public void DarkGoldenrodTest()
        {
            // TODO unit test for the property 'DarkGoldenrod'
        }
        /// <summary>
        /// Test the property 'DarkGray'
        /// </summary>
        [Test]
        public void DarkGrayTest()
        {
            // TODO unit test for the property 'DarkGray'
        }
        /// <summary>
        /// Test the property 'DarkGreen'
        /// </summary>
        [Test]
        public void DarkGreenTest()
        {
            // TODO unit test for the property 'DarkGreen'
        }
        /// <summary>
        /// Test the property 'DarkKhaki'
        /// </summary>
        [Test]
        public void DarkKhakiTest()
        {
            // TODO unit test for the property 'DarkKhaki'
        }
        /// <summary>
        /// Test the property 'DarkMagenta'
        /// </summary>
        [Test]
        public void DarkMagentaTest()
        {
            // TODO unit test for the property 'DarkMagenta'
        }
        /// <summary>
        /// Test the property 'DarkOliveGreen'
        /// </summary>
        [Test]
        public void DarkOliveGreenTest()
        {
            // TODO unit test for the property 'DarkOliveGreen'
        }
        /// <summary>
        /// Test the property 'DarkOrange'
        /// </summary>
        [Test]
        public void DarkOrangeTest()
        {
            // TODO unit test for the property 'DarkOrange'
        }
        /// <summary>
        /// Test the property 'DarkOrchid'
        /// </summary>
        [Test]
        public void DarkOrchidTest()
        {
            // TODO unit test for the property 'DarkOrchid'
        }
        /// <summary>
        /// Test the property 'DarkRed'
        /// </summary>
        [Test]
        public void DarkRedTest()
        {
            // TODO unit test for the property 'DarkRed'
        }
        /// <summary>
        /// Test the property 'DarkSalmon'
        /// </summary>
        [Test]
        public void DarkSalmonTest()
        {
            // TODO unit test for the property 'DarkSalmon'
        }
        /// <summary>
        /// Test the property 'DarkSeaGreen'
        /// </summary>
        [Test]
        public void DarkSeaGreenTest()
        {
            // TODO unit test for the property 'DarkSeaGreen'
        }
        /// <summary>
        /// Test the property 'DarkSlateBlue'
        /// </summary>
        [Test]
        public void DarkSlateBlueTest()
        {
            // TODO unit test for the property 'DarkSlateBlue'
        }
        /// <summary>
        /// Test the property 'DarkSlateGray'
        /// </summary>
        [Test]
        public void DarkSlateGrayTest()
        {
            // TODO unit test for the property 'DarkSlateGray'
        }
        /// <summary>
        /// Test the property 'DarkTurquoise'
        /// </summary>
        [Test]
        public void DarkTurquoiseTest()
        {
            // TODO unit test for the property 'DarkTurquoise'
        }
        /// <summary>
        /// Test the property 'DarkViolet'
        /// </summary>
        [Test]
        public void DarkVioletTest()
        {
            // TODO unit test for the property 'DarkViolet'
        }
        /// <summary>
        /// Test the property 'DeepPink'
        /// </summary>
        [Test]
        public void DeepPinkTest()
        {
            // TODO unit test for the property 'DeepPink'
        }
        /// <summary>
        /// Test the property 'DeepSkyBlue'
        /// </summary>
        [Test]
        public void DeepSkyBlueTest()
        {
            // TODO unit test for the property 'DeepSkyBlue'
        }
        /// <summary>
        /// Test the property 'DimGray'
        /// </summary>
        [Test]
        public void DimGrayTest()
        {
            // TODO unit test for the property 'DimGray'
        }
        /// <summary>
        /// Test the property 'DodgerBlue'
        /// </summary>
        [Test]
        public void DodgerBlueTest()
        {
            // TODO unit test for the property 'DodgerBlue'
        }
        /// <summary>
        /// Test the property 'Firebrick'
        /// </summary>
        [Test]
        public void FirebrickTest()
        {
            // TODO unit test for the property 'Firebrick'
        }
        /// <summary>
        /// Test the property 'FloralWhite'
        /// </summary>
        [Test]
        public void FloralWhiteTest()
        {
            // TODO unit test for the property 'FloralWhite'
        }
        /// <summary>
        /// Test the property 'ForestGreen'
        /// </summary>
        [Test]
        public void ForestGreenTest()
        {
            // TODO unit test for the property 'ForestGreen'
        }
        /// <summary>
        /// Test the property 'Fuchsia'
        /// </summary>
        [Test]
        public void FuchsiaTest()
        {
            // TODO unit test for the property 'Fuchsia'
        }
        /// <summary>
        /// Test the property 'Gainsboro'
        /// </summary>
        [Test]
        public void GainsboroTest()
        {
            // TODO unit test for the property 'Gainsboro'
        }
        /// <summary>
        /// Test the property 'GhostWhite'
        /// </summary>
        [Test]
        public void GhostWhiteTest()
        {
            // TODO unit test for the property 'GhostWhite'
        }
        /// <summary>
        /// Test the property 'Gold'
        /// </summary>
        [Test]
        public void GoldTest()
        {
            // TODO unit test for the property 'Gold'
        }
        /// <summary>
        /// Test the property 'Goldenrod'
        /// </summary>
        [Test]
        public void GoldenrodTest()
        {
            // TODO unit test for the property 'Goldenrod'
        }
        /// <summary>
        /// Test the property 'Gray'
        /// </summary>
        [Test]
        public void GrayTest()
        {
            // TODO unit test for the property 'Gray'
        }
        /// <summary>
        /// Test the property 'Green'
        /// </summary>
        [Test]
        public void GreenTest()
        {
            // TODO unit test for the property 'Green'
        }
        /// <summary>
        /// Test the property 'GreenYellow'
        /// </summary>
        [Test]
        public void GreenYellowTest()
        {
            // TODO unit test for the property 'GreenYellow'
        }
        /// <summary>
        /// Test the property 'Honeydew'
        /// </summary>
        [Test]
        public void HoneydewTest()
        {
            // TODO unit test for the property 'Honeydew'
        }
        /// <summary>
        /// Test the property 'HotPink'
        /// </summary>
        [Test]
        public void HotPinkTest()
        {
            // TODO unit test for the property 'HotPink'
        }
        /// <summary>
        /// Test the property 'IndianRed'
        /// </summary>
        [Test]
        public void IndianRedTest()
        {
            // TODO unit test for the property 'IndianRed'
        }
        /// <summary>
        /// Test the property 'Indigo'
        /// </summary>
        [Test]
        public void IndigoTest()
        {
            // TODO unit test for the property 'Indigo'
        }
        /// <summary>
        /// Test the property 'Ivory'
        /// </summary>
        [Test]
        public void IvoryTest()
        {
            // TODO unit test for the property 'Ivory'
        }
        /// <summary>
        /// Test the property 'Khaki'
        /// </summary>
        [Test]
        public void KhakiTest()
        {
            // TODO unit test for the property 'Khaki'
        }
        /// <summary>
        /// Test the property 'Lavender'
        /// </summary>
        [Test]
        public void LavenderTest()
        {
            // TODO unit test for the property 'Lavender'
        }
        /// <summary>
        /// Test the property 'LavenderBlush'
        /// </summary>
        [Test]
        public void LavenderBlushTest()
        {
            // TODO unit test for the property 'LavenderBlush'
        }
        /// <summary>
        /// Test the property 'LawnGreen'
        /// </summary>
        [Test]
        public void LawnGreenTest()
        {
            // TODO unit test for the property 'LawnGreen'
        }
        /// <summary>
        /// Test the property 'LemonChiffon'
        /// </summary>
        [Test]
        public void LemonChiffonTest()
        {
            // TODO unit test for the property 'LemonChiffon'
        }
        /// <summary>
        /// Test the property 'LightBlue'
        /// </summary>
        [Test]
        public void LightBlueTest()
        {
            // TODO unit test for the property 'LightBlue'
        }
        /// <summary>
        /// Test the property 'LightCoral'
        /// </summary>
        [Test]
        public void LightCoralTest()
        {
            // TODO unit test for the property 'LightCoral'
        }
        /// <summary>
        /// Test the property 'LightCyan'
        /// </summary>
        [Test]
        public void LightCyanTest()
        {
            // TODO unit test for the property 'LightCyan'
        }
        /// <summary>
        /// Test the property 'LightGoldenrodYellow'
        /// </summary>
        [Test]
        public void LightGoldenrodYellowTest()
        {
            // TODO unit test for the property 'LightGoldenrodYellow'
        }
        /// <summary>
        /// Test the property 'LightGreen'
        /// </summary>
        [Test]
        public void LightGreenTest()
        {
            // TODO unit test for the property 'LightGreen'
        }
        /// <summary>
        /// Test the property 'LightGray'
        /// </summary>
        [Test]
        public void LightGrayTest()
        {
            // TODO unit test for the property 'LightGray'
        }
        /// <summary>
        /// Test the property 'LightPink'
        /// </summary>
        [Test]
        public void LightPinkTest()
        {
            // TODO unit test for the property 'LightPink'
        }
        /// <summary>
        /// Test the property 'LightSalmon'
        /// </summary>
        [Test]
        public void LightSalmonTest()
        {
            // TODO unit test for the property 'LightSalmon'
        }
        /// <summary>
        /// Test the property 'LightSeaGreen'
        /// </summary>
        [Test]
        public void LightSeaGreenTest()
        {
            // TODO unit test for the property 'LightSeaGreen'
        }
        /// <summary>
        /// Test the property 'LightSkyBlue'
        /// </summary>
        [Test]
        public void LightSkyBlueTest()
        {
            // TODO unit test for the property 'LightSkyBlue'
        }
        /// <summary>
        /// Test the property 'LightSlateGray'
        /// </summary>
        [Test]
        public void LightSlateGrayTest()
        {
            // TODO unit test for the property 'LightSlateGray'
        }
        /// <summary>
        /// Test the property 'LightSteelBlue'
        /// </summary>
        [Test]
        public void LightSteelBlueTest()
        {
            // TODO unit test for the property 'LightSteelBlue'
        }
        /// <summary>
        /// Test the property 'LightYellow'
        /// </summary>
        [Test]
        public void LightYellowTest()
        {
            // TODO unit test for the property 'LightYellow'
        }
        /// <summary>
        /// Test the property 'Lime'
        /// </summary>
        [Test]
        public void LimeTest()
        {
            // TODO unit test for the property 'Lime'
        }
        /// <summary>
        /// Test the property 'LimeGreen'
        /// </summary>
        [Test]
        public void LimeGreenTest()
        {
            // TODO unit test for the property 'LimeGreen'
        }
        /// <summary>
        /// Test the property 'Linen'
        /// </summary>
        [Test]
        public void LinenTest()
        {
            // TODO unit test for the property 'Linen'
        }
        /// <summary>
        /// Test the property 'Magenta'
        /// </summary>
        [Test]
        public void MagentaTest()
        {
            // TODO unit test for the property 'Magenta'
        }
        /// <summary>
        /// Test the property 'Maroon'
        /// </summary>
        [Test]
        public void MaroonTest()
        {
            // TODO unit test for the property 'Maroon'
        }
        /// <summary>
        /// Test the property 'MediumAquamarine'
        /// </summary>
        [Test]
        public void MediumAquamarineTest()
        {
            // TODO unit test for the property 'MediumAquamarine'
        }
        /// <summary>
        /// Test the property 'MediumBlue'
        /// </summary>
        [Test]
        public void MediumBlueTest()
        {
            // TODO unit test for the property 'MediumBlue'
        }
        /// <summary>
        /// Test the property 'MediumOrchid'
        /// </summary>
        [Test]
        public void MediumOrchidTest()
        {
            // TODO unit test for the property 'MediumOrchid'
        }
        /// <summary>
        /// Test the property 'MediumPurple'
        /// </summary>
        [Test]
        public void MediumPurpleTest()
        {
            // TODO unit test for the property 'MediumPurple'
        }
        /// <summary>
        /// Test the property 'MediumSeaGreen'
        /// </summary>
        [Test]
        public void MediumSeaGreenTest()
        {
            // TODO unit test for the property 'MediumSeaGreen'
        }
        /// <summary>
        /// Test the property 'MediumSlateBlue'
        /// </summary>
        [Test]
        public void MediumSlateBlueTest()
        {
            // TODO unit test for the property 'MediumSlateBlue'
        }
        /// <summary>
        /// Test the property 'MediumSpringGreen'
        /// </summary>
        [Test]
        public void MediumSpringGreenTest()
        {
            // TODO unit test for the property 'MediumSpringGreen'
        }
        /// <summary>
        /// Test the property 'MediumTurquoise'
        /// </summary>
        [Test]
        public void MediumTurquoiseTest()
        {
            // TODO unit test for the property 'MediumTurquoise'
        }
        /// <summary>
        /// Test the property 'MediumVioletRed'
        /// </summary>
        [Test]
        public void MediumVioletRedTest()
        {
            // TODO unit test for the property 'MediumVioletRed'
        }
        /// <summary>
        /// Test the property 'MidnightBlue'
        /// </summary>
        [Test]
        public void MidnightBlueTest()
        {
            // TODO unit test for the property 'MidnightBlue'
        }
        /// <summary>
        /// Test the property 'MintCream'
        /// </summary>
        [Test]
        public void MintCreamTest()
        {
            // TODO unit test for the property 'MintCream'
        }
        /// <summary>
        /// Test the property 'MistyRose'
        /// </summary>
        [Test]
        public void MistyRoseTest()
        {
            // TODO unit test for the property 'MistyRose'
        }
        /// <summary>
        /// Test the property 'Moccasin'
        /// </summary>
        [Test]
        public void MoccasinTest()
        {
            // TODO unit test for the property 'Moccasin'
        }
        /// <summary>
        /// Test the property 'NavajoWhite'
        /// </summary>
        [Test]
        public void NavajoWhiteTest()
        {
            // TODO unit test for the property 'NavajoWhite'
        }
        /// <summary>
        /// Test the property 'Navy'
        /// </summary>
        [Test]
        public void NavyTest()
        {
            // TODO unit test for the property 'Navy'
        }
        /// <summary>
        /// Test the property 'OldLace'
        /// </summary>
        [Test]
        public void OldLaceTest()
        {
            // TODO unit test for the property 'OldLace'
        }
        /// <summary>
        /// Test the property 'Olive'
        /// </summary>
        [Test]
        public void OliveTest()
        {
            // TODO unit test for the property 'Olive'
        }
        /// <summary>
        /// Test the property 'OliveDrab'
        /// </summary>
        [Test]
        public void OliveDrabTest()
        {
            // TODO unit test for the property 'OliveDrab'
        }
        /// <summary>
        /// Test the property 'Orange'
        /// </summary>
        [Test]
        public void OrangeTest()
        {
            // TODO unit test for the property 'Orange'
        }
        /// <summary>
        /// Test the property 'OrangeRed'
        /// </summary>
        [Test]
        public void OrangeRedTest()
        {
            // TODO unit test for the property 'OrangeRed'
        }
        /// <summary>
        /// Test the property 'Orchid'
        /// </summary>
        [Test]
        public void OrchidTest()
        {
            // TODO unit test for the property 'Orchid'
        }
        /// <summary>
        /// Test the property 'PaleGoldenrod'
        /// </summary>
        [Test]
        public void PaleGoldenrodTest()
        {
            // TODO unit test for the property 'PaleGoldenrod'
        }
        /// <summary>
        /// Test the property 'PaleGreen'
        /// </summary>
        [Test]
        public void PaleGreenTest()
        {
            // TODO unit test for the property 'PaleGreen'
        }
        /// <summary>
        /// Test the property 'PaleTurquoise'
        /// </summary>
        [Test]
        public void PaleTurquoiseTest()
        {
            // TODO unit test for the property 'PaleTurquoise'
        }
        /// <summary>
        /// Test the property 'PaleVioletRed'
        /// </summary>
        [Test]
        public void PaleVioletRedTest()
        {
            // TODO unit test for the property 'PaleVioletRed'
        }
        /// <summary>
        /// Test the property 'PapayaWhip'
        /// </summary>
        [Test]
        public void PapayaWhipTest()
        {
            // TODO unit test for the property 'PapayaWhip'
        }
        /// <summary>
        /// Test the property 'PeachPuff'
        /// </summary>
        [Test]
        public void PeachPuffTest()
        {
            // TODO unit test for the property 'PeachPuff'
        }
        /// <summary>
        /// Test the property 'Peru'
        /// </summary>
        [Test]
        public void PeruTest()
        {
            // TODO unit test for the property 'Peru'
        }
        /// <summary>
        /// Test the property 'Pink'
        /// </summary>
        [Test]
        public void PinkTest()
        {
            // TODO unit test for the property 'Pink'
        }
        /// <summary>
        /// Test the property 'Plum'
        /// </summary>
        [Test]
        public void PlumTest()
        {
            // TODO unit test for the property 'Plum'
        }
        /// <summary>
        /// Test the property 'PowderBlue'
        /// </summary>
        [Test]
        public void PowderBlueTest()
        {
            // TODO unit test for the property 'PowderBlue'
        }
        /// <summary>
        /// Test the property 'Purple'
        /// </summary>
        [Test]
        public void PurpleTest()
        {
            // TODO unit test for the property 'Purple'
        }
        /// <summary>
        /// Test the property 'Red'
        /// </summary>
        [Test]
        public void RedTest()
        {
            // TODO unit test for the property 'Red'
        }
        /// <summary>
        /// Test the property 'RosyBrown'
        /// </summary>
        [Test]
        public void RosyBrownTest()
        {
            // TODO unit test for the property 'RosyBrown'
        }
        /// <summary>
        /// Test the property 'RoyalBlue'
        /// </summary>
        [Test]
        public void RoyalBlueTest()
        {
            // TODO unit test for the property 'RoyalBlue'
        }
        /// <summary>
        /// Test the property 'SaddleBrown'
        /// </summary>
        [Test]
        public void SaddleBrownTest()
        {
            // TODO unit test for the property 'SaddleBrown'
        }
        /// <summary>
        /// Test the property 'Salmon'
        /// </summary>
        [Test]
        public void SalmonTest()
        {
            // TODO unit test for the property 'Salmon'
        }
        /// <summary>
        /// Test the property 'SandyBrown'
        /// </summary>
        [Test]
        public void SandyBrownTest()
        {
            // TODO unit test for the property 'SandyBrown'
        }
        /// <summary>
        /// Test the property 'SeaGreen'
        /// </summary>
        [Test]
        public void SeaGreenTest()
        {
            // TODO unit test for the property 'SeaGreen'
        }
        /// <summary>
        /// Test the property 'SeaShell'
        /// </summary>
        [Test]
        public void SeaShellTest()
        {
            // TODO unit test for the property 'SeaShell'
        }
        /// <summary>
        /// Test the property 'Sienna'
        /// </summary>
        [Test]
        public void SiennaTest()
        {
            // TODO unit test for the property 'Sienna'
        }
        /// <summary>
        /// Test the property 'Silver'
        /// </summary>
        [Test]
        public void SilverTest()
        {
            // TODO unit test for the property 'Silver'
        }
        /// <summary>
        /// Test the property 'SkyBlue'
        /// </summary>
        [Test]
        public void SkyBlueTest()
        {
            // TODO unit test for the property 'SkyBlue'
        }
        /// <summary>
        /// Test the property 'SlateBlue'
        /// </summary>
        [Test]
        public void SlateBlueTest()
        {
            // TODO unit test for the property 'SlateBlue'
        }
        /// <summary>
        /// Test the property 'SlateGray'
        /// </summary>
        [Test]
        public void SlateGrayTest()
        {
            // TODO unit test for the property 'SlateGray'
        }
        /// <summary>
        /// Test the property 'Snow'
        /// </summary>
        [Test]
        public void SnowTest()
        {
            // TODO unit test for the property 'Snow'
        }
        /// <summary>
        /// Test the property 'SpringGreen'
        /// </summary>
        [Test]
        public void SpringGreenTest()
        {
            // TODO unit test for the property 'SpringGreen'
        }
        /// <summary>
        /// Test the property 'SteelBlue'
        /// </summary>
        [Test]
        public void SteelBlueTest()
        {
            // TODO unit test for the property 'SteelBlue'
        }
        /// <summary>
        /// Test the property 'Tan'
        /// </summary>
        [Test]
        public void TanTest()
        {
            // TODO unit test for the property 'Tan'
        }
        /// <summary>
        /// Test the property 'Teal'
        /// </summary>
        [Test]
        public void TealTest()
        {
            // TODO unit test for the property 'Teal'
        }
        /// <summary>
        /// Test the property 'Thistle'
        /// </summary>
        [Test]
        public void ThistleTest()
        {
            // TODO unit test for the property 'Thistle'
        }
        /// <summary>
        /// Test the property 'Tomato'
        /// </summary>
        [Test]
        public void TomatoTest()
        {
            // TODO unit test for the property 'Tomato'
        }
        /// <summary>
        /// Test the property 'Turquoise'
        /// </summary>
        [Test]
        public void TurquoiseTest()
        {
            // TODO unit test for the property 'Turquoise'
        }
        /// <summary>
        /// Test the property 'Violet'
        /// </summary>
        [Test]
        public void VioletTest()
        {
            // TODO unit test for the property 'Violet'
        }
        /// <summary>
        /// Test the property 'Wheat'
        /// </summary>
        [Test]
        public void WheatTest()
        {
            // TODO unit test for the property 'Wheat'
        }
        /// <summary>
        /// Test the property 'White'
        /// </summary>
        [Test]
        public void WhiteTest()
        {
            // TODO unit test for the property 'White'
        }
        /// <summary>
        /// Test the property 'WhiteSmoke'
        /// </summary>
        [Test]
        public void WhiteSmokeTest()
        {
            // TODO unit test for the property 'WhiteSmoke'
        }
        /// <summary>
        /// Test the property 'Yellow'
        /// </summary>
        [Test]
        public void YellowTest()
        {
            // TODO unit test for the property 'Yellow'
        }
        /// <summary>
        /// Test the property 'YellowGreen'
        /// </summary>
        [Test]
        public void YellowGreenTest()
        {
            // TODO unit test for the property 'YellowGreen'
        }
        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Test]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'G'
        /// </summary>
        [Test]
        public void GTest()
        {
            // TODO unit test for the property 'G'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Test]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }
        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Test]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }
        /// <summary>
        /// Test the property 'IsKnownColor'
        /// </summary>
        [Test]
        public void IsKnownColorTest()
        {
            // TODO unit test for the property 'IsKnownColor'
        }
        /// <summary>
        /// Test the property 'IsEmpty'
        /// </summary>
        [Test]
        public void IsEmptyTest()
        {
            // TODO unit test for the property 'IsEmpty'
        }
        /// <summary>
        /// Test the property 'IsNamedColor'
        /// </summary>
        [Test]
        public void IsNamedColorTest()
        {
            // TODO unit test for the property 'IsNamedColor'
        }
        /// <summary>
        /// Test the property 'IsSystemColor'
        /// </summary>
        [Test]
        public void IsSystemColorTest()
        {
            // TODO unit test for the property 'IsSystemColor'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Empty'
        /// </summary>
        [Test]
        public void EmptyTest()
        {
            // TODO unit test for the property 'Empty'
        }

    }

}
