/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ComparisonChangesCategoryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComparisonChangesCategoryDtoTests
    {
        // TODO uncomment below to declare an instance variable for ComparisonChangesCategoryDto
        //private ComparisonChangesCategoryDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComparisonChangesCategoryDto
            //instance = new ComparisonChangesCategoryDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComparisonChangesCategoryDto
        /// </summary>
        [Test]
        public void ComparisonChangesCategoryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComparisonChangesCategoryDto
            //Assert.IsInstanceOfType<ComparisonChangesCategoryDto> (instance, "variable 'instance' is a ComparisonChangesCategoryDto");
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Test]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }

    }

}
