/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ComparisonMetadataValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComparisonMetadataValuesTests
    {
        // TODO uncomment below to declare an instance variable for ComparisonMetadataValues
        //private ComparisonMetadataValues instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComparisonMetadataValues
            //instance = new ComparisonMetadataValues();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComparisonMetadataValues
        /// </summary>
        [Test]
        public void ComparisonMetadataValuesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComparisonMetadataValues
            //Assert.IsInstanceOfType<ComparisonMetadataValues> (instance, "variable 'instance' is a ComparisonMetadataValues");
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'LastSaveBy'
        /// </summary>
        [Test]
        public void LastSaveByTest()
        {
            // TODO unit test for the property 'LastSaveBy'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

    }

}
