/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ComparisonStyleChange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComparisonStyleChangeTests
    {
        // TODO uncomment below to declare an instance variable for ComparisonStyleChange
        //private ComparisonStyleChange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComparisonStyleChange
            //instance = new ComparisonStyleChange();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComparisonStyleChange
        /// </summary>
        [Test]
        public void ComparisonStyleChangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComparisonStyleChange
            //Assert.IsInstanceOfType<ComparisonStyleChange> (instance, "variable 'instance' is a ComparisonStyleChange");
        }

        /// <summary>
        /// Test the property 'ChangedProperty'
        /// </summary>
        [Test]
        public void ChangedPropertyTest()
        {
            // TODO unit test for the property 'ChangedProperty'
        }

    }

}
