/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ComparisonRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComparisonRequestTests
    {
        // TODO uncomment below to declare an instance variable for ComparisonRequest
        //private ComparisonRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComparisonRequest
            //instance = new ComparisonRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComparisonRequest
        /// </summary>
        [Test]
        public void ComparisonRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComparisonRequest
            //Assert.IsInstanceOfType<ComparisonRequest> (instance, "variable 'instance' is a ComparisonRequest");
        }

        /// <summary>
        /// Test the property 'SourceFile'
        /// </summary>
        [Test]
        public void SourceFileTest()
        {
            // TODO unit test for the property 'SourceFile'
        }
        /// <summary>
        /// Test the property 'TargetFiles'
        /// </summary>
        [Test]
        public void TargetFilesTest()
        {
            // TODO unit test for the property 'TargetFiles'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Test]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }

    }

}
