/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ComparisonRequestSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComparisonRequestSettingsTests
    {
        // TODO uncomment below to declare an instance variable for ComparisonRequestSettings
        //private ComparisonRequestSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComparisonRequestSettings
            //instance = new ComparisonRequestSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComparisonRequestSettings
        /// </summary>
        [Test]
        public void ComparisonRequestSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComparisonRequestSettings
            //Assert.IsInstanceOfType<ComparisonRequestSettings> (instance, "variable 'instance' is a ComparisonRequestSettings");
        }

        /// <summary>
        /// Test the property 'GenerateSummaryPage'
        /// </summary>
        [Test]
        public void GenerateSummaryPageTest()
        {
            // TODO unit test for the property 'GenerateSummaryPage'
        }
        /// <summary>
        /// Test the property 'ShowDeletedContent'
        /// </summary>
        [Test]
        public void ShowDeletedContentTest()
        {
            // TODO unit test for the property 'ShowDeletedContent'
        }
        /// <summary>
        /// Test the property 'StyleChangeDetection'
        /// </summary>
        [Test]
        public void StyleChangeDetectionTest()
        {
            // TODO unit test for the property 'StyleChangeDetection'
        }
        /// <summary>
        /// Test the property 'InsertedItemsStyle'
        /// </summary>
        [Test]
        public void InsertedItemsStyleTest()
        {
            // TODO unit test for the property 'InsertedItemsStyle'
        }
        /// <summary>
        /// Test the property 'DeletedItemsStyle'
        /// </summary>
        [Test]
        public void DeletedItemsStyleTest()
        {
            // TODO unit test for the property 'DeletedItemsStyle'
        }
        /// <summary>
        /// Test the property 'StyleChangedItemsStyle'
        /// </summary>
        [Test]
        public void StyleChangedItemsStyleTest()
        {
            // TODO unit test for the property 'StyleChangedItemsStyle'
        }
        /// <summary>
        /// Test the property 'WordsSeparatorChars'
        /// </summary>
        [Test]
        public void WordsSeparatorCharsTest()
        {
            // TODO unit test for the property 'WordsSeparatorChars'
        }
        /// <summary>
        /// Test the property 'UseFramesForDelInsElements'
        /// </summary>
        [Test]
        public void UseFramesForDelInsElementsTest()
        {
            // TODO unit test for the property 'UseFramesForDelInsElements'
        }
        /// <summary>
        /// Test the property 'DetailLevel'
        /// </summary>
        [Test]
        public void DetailLevelTest()
        {
            // TODO unit test for the property 'DetailLevel'
        }
        /// <summary>
        /// Test the property 'CalculateComponentCoordinates'
        /// </summary>
        [Test]
        public void CalculateComponentCoordinatesTest()
        {
            // TODO unit test for the property 'CalculateComponentCoordinates'
        }
        /// <summary>
        /// Test the property 'CloneMetadata'
        /// </summary>
        [Test]
        public void CloneMetadataTest()
        {
            // TODO unit test for the property 'CloneMetadata'
        }
        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Test]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
        /// <summary>
        /// Test the property 'PasswordSaveOption'
        /// </summary>
        [Test]
        public void PasswordSaveOptionTest()
        {
            // TODO unit test for the property 'PasswordSaveOption'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'MarkDeletedInsertedContentDeep'
        /// </summary>
        [Test]
        public void MarkDeletedInsertedContentDeepTest()
        {
            // TODO unit test for the property 'MarkDeletedInsertedContentDeep'
        }

    }

}
