/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;
using GroupDocs.Comparison.Cloud.Sdk.Client;
using System.Reflection;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing StyleSettingsValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StyleSettingsValuesTests
    {
        // TODO uncomment below to declare an instance variable for StyleSettingsValues
        //private StyleSettingsValues instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StyleSettingsValues
            //instance = new StyleSettingsValues();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StyleSettingsValues
        /// </summary>
        [Test]
        public void StyleSettingsValuesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StyleSettingsValues
            //Assert.IsInstanceOfType<StyleSettingsValues> (instance, "variable 'instance' is a StyleSettingsValues");
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'BeginSeparatorString'
        /// </summary>
        [Test]
        public void BeginSeparatorStringTest()
        {
            // TODO unit test for the property 'BeginSeparatorString'
        }
        /// <summary>
        /// Test the property 'EndSeparatorString'
        /// </summary>
        [Test]
        public void EndSeparatorStringTest()
        {
            // TODO unit test for the property 'EndSeparatorString'
        }

    }

}
