/* 
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using GroupDocs.Comparison.Cloud.Sdk.Client;
using GroupDocs.Comparison.Cloud.Sdk.Api;
using GroupDocs.Comparison.Cloud.Sdk.Model;

namespace GroupDocs.Comparison.Cloud.Sdk.Test
{
    /// <summary>
    ///  Class for testing ChangesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ChangesApiTests
    {
        private ChangesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ChangesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ChangesApi
            //Assert.IsInstanceOfType(typeof(ChangesApi), instance, "instance is a ChangesApi");
        }

        
        /// <summary>
        /// Test PostCategoriesChanges
        /// </summary>
        [Test]
        public void PostCategoriesChangesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //string categoriesType = null;
            //var response = instance.PostCategoriesChanges(request, categoriesType);
            //Assert.IsInstanceOf<List<ComparisonChangesCategoryDto>> (response, "response is List<ComparisonChangesCategoryDto>");
        }
        
        /// <summary>
        /// Test PostChanges
        /// </summary>
        [Test]
        public void PostChangesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //var response = instance.PostChanges(request);
            //Assert.IsInstanceOf<List<ComparisonChange>> (response, "response is List<ComparisonChange>");
        }
        
        /// <summary>
        /// Test PutChangesDocument
        /// </summary>
        [Test]
        public void PutChangesDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //string outPath = null;
            //var response = instance.PutChangesDocument(request, outPath);
            //Assert.IsInstanceOf<Link> (response, "response is Link");
        }
        
        /// <summary>
        /// Test PutChangesDocumentStream
        /// </summary>
        [Test]
        public void PutChangesDocumentStreamTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //var response = instance.PutChangesDocumentStream(request);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test PutChangesImages
        /// </summary>
        [Test]
        public void PutChangesImagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //string outFolder = null;
            //var response = instance.PutChangesImages(request, outFolder);
            //Assert.IsInstanceOf<List<Link>> (response, "response is List<Link>");
        }
        
        /// <summary>
        /// Test PutChangesImagesStream
        /// </summary>
        [Test]
        public void PutChangesImagesStreamTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComparisonRequest request = null;
            //var response = instance.PutChangesImagesStream(request);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
    }

}
